# Generated by Django 2.1.15 on 2021-04-25 01:18

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0016_auto_20180329_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_newsblog.Article'),
        ),
        migrations.AlterField(
            model_name='newsblogconfigtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_newsblog.NewsBlogConfig'),
        ),
    ]
